env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/recommended'
plugins:
  - vue
#  - '@typescript-eslint'
parserOptions:
  project: ./tsconfig.json
  parser: '@typescript-eslint/parser'
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/no-use-before-define': [error, {functions: false, typedefs: false}]
  '@typescript-eslint/indent': [error, 2]
  '@typescript-eslint/interface-name-prefix': [error, always]
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: semi
        requireLast: false
